[*]
wallpaper_mode=color
wallpaper_common=1
wallpaper=/home/frost/atEase/atease-tile.png
desktop_bg=#000000
desktop_fg=#3D3846
desktop_shadow=#000000
desktop_font=ChicagoFLF Medium 7
folder=/home/frost/Desktop
show_wm_menu=0
sort=mtime;ascending;
show_documents=0
show_home=0
show_trash=0
show_mounts=0

[LimeWire.desktop]
x=285
y=201

[Weather Channel.desktop]
x=422
y=199

[America Online.desktop]
x=154
y=200

[FlyingToasters.desktop]
x=554
y=202

[Encarta.desktop]
x=152
y=321

[Winamp.desktop]
x=422
y=89

[Retropie.desktop]
x=555
y=88

[Macintosh-HD.desktop]
x=425
y=317

[Terminal.desktop]
x=286
y=318

[MacOS9.desktop]
x=289
y=88

[Chromium-70.desktop]
x=152
y=90

[trash:///]
x=559
y=321

